### PR TITLE
Clarify freeze object trigger

### PR DESCRIPTION
**Pull request by mardaravicius**

### CODE REVIEW

**Comment by mardaravicius** [comment]
one step at a time :)

**Comment by Divy1211** [comment]
Kirby and I are working on generating the json from ASP docs, so if you're working on something like that, it may be advisable to hold off a bit

**Comment by mardaravicius** [comment]
no, just fixing stuf i found was missing when I looked at some specific stuff.
does that include all changes and for missing conditions/effects? since might want to make other corrections prs

**Comment by Divy1211** [comment]
yea, go ahead and make the corrections if you want!

**Comment by Divy1211** [comment]
It will include missing stuff, eventually, yes

**Review by Divy1211 — APPROVED** [review]

**Pull request merged**
